### ISSUE TITLE
Drifting base unit even when LiDAR is static

### ISSUE THREAD

**Issue by Dinatorehanova** [RobustFieldAutonomyLab/LeGO-LOAM#97]
Hi @TixiaoShan ,

I am having this issue like even when my LiDAR is static it seems to be moving in the LeGO-LOAM kind of drifting.

![image](https://user-images.githubusercontent.com/51459647/60076080-e7127580-96e3-11e9-9ebc-6e1f2318cfbd.png)

Any thought like what might causing this ?

Thanks

**Comment by gkharish** [comment]
Hello, 
From the image you shared, it seems that you are testing it indoor. The algorithm works better with the identification of the ground plane. In the indoor setting, I guess you need to modify the parameters of groundScanInd in utility.h file. 
Otherwise, simply test it outside in a bit open space. 
Thanks!
